### ISSUE TITLE
我已经将special.lua文件添加到了expansions/script文件夹，但是好像没生效？

### ISSUE THREAD

**Issue by yehuoshun** [purerosefallen/specials#16]
Pick your favorite rule, and put special.lua into your server's expansions/script directory.

I've added the special.lua file to the expansions/script folder, but it seems not to be working
![image](https://github.com/user-attachments/assets/ad96979c-01f1-41a5-aa22-c80e574ae3ad)

**Comment by purerosefallen** [comment]
Use the server from https://github.com/purerosefallen/specials which supports aux.PreloadUds

**Comment by yehuoshun** [comment]
> Use the server from https://github.com/purerosefallen/ygopro which supports aux.PreloadUds

It's been resolved, thank you.
